@Lab_Project.Server_HostAddress = https://localhost:7262

GET {{Lab_Project.Server_HostAddress}}/product/8
Accept: application/json

###
PATCH {{Lab_Project.Server_HostAddress}}/product/5

{
  "id": 5,
  "name": "iPhone 15 Pro",
  "category": "Electronics",
  "price": 1299.99
}
